modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="All rights reserved"
issueTrackerURL="https://github.com/TwelveIterationMods/Fertilization/issues"

[[mods]]
modId="fertilization"
version="${file.jarVersion}"
displayName="Fertilization"
displayURL="https://mods.twelveiterations.com/mc/fertilization"
logoFile="fertilization-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Adds additional variants of bone meal for all your fertilization needs.
'''

[[dependencies.fertilization]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.fertilization]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.fertilization]]
    modId="balm"
    mandatory=true
    versionRange="${balm_version_range}"
    ordering="NONE"
    side="BOTH"
